#!/bin/bash
# =========================================================================== #
#                                                                             #
#                 ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                 #
#                 ┃   ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗   ┃                 #
#                 ┃   ████╗  ██║██╔═████╗██║   ██║██╔══██╗  ┃                 #
#                 ┃   ██╔██╗ ██║██║██╔██║██║   ██║███████║  ┃                 #
#                 ┃   ██║╚██╗██║████╔╝██║╚██╗ ██╔╝██╔══██║  ┃                 #
#                 ┃   ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║  ┃                 #
#                 ┃   ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝  ┃                 #
#                 ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                 #
#                                                                             #
#                        This machine kills fascists.                         #
#                                                                             #
# =========================================================================== #

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
WORKSPACE_DIR=$(dirname $SCRIPT_DIR)

if [ -z "${NOVIX_WORKSPACE}" ]; then
  echo "Setting NOVIX_WORKSPACE=$WORKSPACE_DIR in ~/.bashrc"
  echo "export NOVIX_WORKSPACE=$WORKSPACE_DIR" >> ~/.bashrc
  echo ""
  echo "Reminder:"
  echo "  source ~/.bashrc"
  echo ""
fi

$NOVIX_WORKSPACE/bin/novix-install-local $(hostname)

echo ""
echo "Workspace is configured and dependencies are installed!"
echo ""
