#!/bin/bash
# =========================================================================== #
#                                                                             #
#                 +-----------------------------------------+                 #
#                 |   ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗   |                 #
#                 |   ████╗  ██║██╔═████╗██║   ██║██╔══██╗  |                 #
#                 |   ██╔██╗ ██║██║██╔██║██║   ██║███████║  |                 #
#                 |   ██║╚██╗██║████╔╝██║╚██╗ ██╔╝██╔══██║  |                 #
#                 |   ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║  |                 #
#                 |   ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝  |                 #
#                 +-----------------------------------------+                 #
#                                                                             #
#                        This machine kills fascists.                         #
#                                                                             #
# =========================================================================== #
#
# network-scan-ipv4-remote is a collection of useful nmap commands.
#
# Use it just like you would use nmap, however it will run a handful of my
# favorite scans against a target.
#
# Useful to grab a quick fingerprint of a remote target for any lawful open
# source intelligence purposes.
#
# Requires "vulscan" to scan for vulnerabilities

DATE=$(date '+%Y-%m-%d')

# Set nmap common to default value 'nmap', note: this can be overloaded to add
# common flags passed to all the commands below.
#
# For example to run the commands as IPv6 you just:
#
#     NMAP_COMMON="nmap -6" ./_nmap
NMAP_COMMON="${NMAP_COMMON:-nmap}"

TARGET=$@ # Target is the full nmap target, host, and other flags
REMOTE=$1 # Remote is the remote host only

# Kill any previous running scans in the background
sudo -E pkill -f nmapworker

## Surface glance (ping scan only) to stdout
# -n  Never do DNS resolution
# -sn Ping Scan - disable port scan
echo ""
echo "---[ Surface Scan ]------------------------------------------------------------------"
sudo -E $NMAP_COMMON -n -sn $TARGET
echo "---[ Surface Scan ]------------------------------------------------------------------"
echo ""

echo "---[ Full Scans ]--------------------------------------------------------------------"
## Fast scan, just the basics:
# -A   Enable OS detection, version detection, script scanning, and traceroute
# -sC  Default script
# -sV  Probe open ports and determine service version
echo "  -> Nmap: Starting Basic Port Scan..."
sudo -E LABEL=nmapworker $NMAP_COMMON -sC -sV -A $TARGET > $HOME/out/$REMOTE-$DATE.nmap.ports 2>&1 &

## [ Full scan ]
# -O   Operating system
# -sC  Default script
# -sV  Probe open ports and determine service version
# -p-  Probe all ports (Note: '-p' is port ranges)
# -v   Increase verbosity level
# -A   Enable OS detection, version detection, script scanning, and traceroute
#
# --min-rate  Send packets no slower than <number> per second
sudo -E LABEL=nmapworker $NMAP_COMMON -sC -sV -p- -v -A --min-rate 5000 $TARGET > $HOME/out/$REMOTE-$DATE.nmap.all.ports 2>&1 &

## [ Windows scan ]
#
# -Pn  No Ping
sudo -E LABEL=nmapworker $NMAP_COMMON -sC -sV -Pn $TARGET > $HOME/out/$REMOTE-$DATE.nmap.ping.ports 2>&1 &


# Basic HTTP Scan
echo "  -> Nmap: Starting Basic HTTP Scan..."
sudo -E LABEL=nmapworker $NMAP_COMMON --script=http-headers $TARGET > $HOME/out/$REMOTE-$DATE.nmap.http 2>&1 &

# Vulnerability (CVE) Scan
echo "  -> Nmap: Starting CVE Scan..."
sudo -E LABEL=nmapworker $NMAP_COMMON -sV --script=vulscan/vulscan.nse $TARGET > $HOME/out/$REMOTE-$DATE.nmap.cve 2>&1 &
echo "---[ Full Scans ]--------------------------------------------------------------------"

echo ""
echo "Scripts will finish in the background."
echo "See $HOME/out/*$REMOTE* files for results"
echo ""
