#!/bin/bash
# =========================================================================== #
#            MIT License Copyright (c) 2022 Kris Nóva <kris@nivenly.com>      #
#                                                                             #
#                 ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                 #
#                 ┃   ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗   ┃                 #
#                 ┃   ████╗  ██║██╔═████╗██║   ██║██╔══██╗  ┃                 #
#                 ┃   ██╔██╗ ██║██║██╔██║██║   ██║███████║  ┃                 #
#                 ┃   ██║╚██╗██║████╔╝██║╚██╗ ██╔╝██╔══██║  ┃                 #
#                 ┃   ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║  ┃                 #
#                 ┃   ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝  ┃                 #
#                 ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                 #
#                                                                             #
#                        This machine kills fascists.                         #
#                                                                             #
# =========================================================================== #
#
# This script will provision the "novix" user data.

function help() {
    echo ""
    echo "===================================================================="
    echo " Used to provision a local machine with the 'novix' user data.      "
    echo ""
    echo " [Usage]:  _novix <hostname>"
    echo ""
    echo ""
    echo "===================================================================="
    echo ""
    exit
}

# Usage and help
if [ -z "$1" ]; then help; fi
if [ "$1" = "help" ]; then help; fi
if [ "$1" = "--help" ]; then help; fi
if [ "$1" = "-h" ]; then help; fi
if [ "$UID" != "0" ]; then echo '**Must be ran as root user with privileges!**'; exit; fi
H=$1 # Variable to store "Hostname"

# User
echo "  -> Creating User: novix"
useradd \
  --groups wheel \
  --system \
  --shell /bin/bash \
  --home-dir /home/novix \
  novix

# Hostname
echo "  -> Setting Hostname: $H"
echo $H > /etc/hostname
hostname $(cat /etc/hostname)
hostnamectl hostname $(cat /etc/hostname)

# Permissions
# Do NOT use ${HOME} here as this runs as root and will break SSH!
echo "  -> Setting /home/novix permissions"
mkdir -p /home/novix/.ssh
chown -R novix:novix /home/novix
chmod 700 /home/novix/.ssh
echo "  -> 700 /home/novix/.ssh"
chmod 600 /home/novix/.ssh/*
echo "  -> 600 /home/novix/.ssh/*"